name: TheRealMediaCompany
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50183
title: The Real Media Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#323232'
    - '#ffffff'
    - '#a6a6a6'
    - '#45b8e6'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
