name: TheRealMediaCompany
favicon: null
layout_spectrum: 0.00238
typography_spectrum: 0.99885
title: The Real Media Company
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#435B78'
    - '#C5C5C5'
    - '#409CCC'
    - '#F3C67F'
  brandStrength: 0.5017921
  lightness: 0.1774193
  saturation: 0.7849463
  rhythmicContrast: 0.7992831
purpose: []
